palette:
  top: '#4a4a4a'
  bottom: '#4e4e4e'
  bg: '#ffffff'
  sidebar: '#ffffff'
  sidebarborders: '#d0d0d0'
  footer: '#161617'
  button: '#0073b6'
  buttonhover: '#00517f'
  titleslogan: '#ffffff'
  text: '#3b3b3b'
  link: '#0073b6'
logo: 'public://color/hadiber_theme-7a4eb7eb/logo.svg'
stylesheets:
  - 'public://color/hadiber_theme-7a4eb7eb/colors.css'
files:
  - 'public://color/hadiber_theme-7a4eb7eb/logo.svg'
  - 'public://color/hadiber_theme-7a4eb7eb/colors.css'
